2017-04-17 15:06:28,502 [Thread-2:8272] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-18 13:10:58,964 [Thread-2:9544] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-18 13:10:58,964 [Thread-3:404] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-18 15:48:57,572 [Thread-8:9336] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-18 15:57:26,684 [Thread-32:10136] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/upload/kindeditor
2017-04-18 16:10:46,190 [Thread-50:4840] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/upload/kindeditor
2017-04-18 16:12:52,842 [Thread-5:3456] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/upload/kindeditor
2017-04-18 17:36:16,703 [Thread-8:7664] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 11:54:45,318 [Thread-3:3800] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 11:54:45,318 [Thread-2:1568] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 11:54:51,700 [Thread-6:3956] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 13:03:56,776 [Thread-5:5956] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 15:15:11,313 [Thread-5:2372] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 15:42:41,308 [Thread-12:5868] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 15:42:42,493 [Thread-14:6644] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-26 15:47:09,785 [Thread-2:4040] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login_reg
Traceback (most recent call last):
  File "F:\DjangoSpace\Graduate\QandA-env\lib\site-packages\django\core\handlers\base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view home.views.login_reg didn't return an HttpResponse object. It returned None instead.
2017-04-26 15:51:29,345 [Thread-4:6968] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login_reg
Traceback (most recent call last):
  File "F:\DjangoSpace\Graduate\QandA-env\lib\site-packages\django\core\handlers\base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view home.views.login_reg didn't return an HttpResponse object. It returned None instead.
2017-04-26 15:59:22,874 [Thread-10:6740] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout
Traceback (most recent call last):
  File "F:\DjangoSpace\Graduate\QandA-env\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\DjangoSpace\Graduate\QandA-env\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "F:\DjangoSpace\Graduate\QandA\home\views.py", line 68, in logout
    print client.mobile, 'logout'
AttributeError: 'NoneType' object has no attribute 'mobile'
2017-04-26 16:43:07,243 [Thread-72:1368] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout
Traceback (most recent call last):
  File "F:\DjangoSpace\Graduate\QandA-env\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\DjangoSpace\Graduate\QandA-env\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "F:\DjangoSpace\Graduate\QandA\home\views.py", line 68, in logout
    print client.mobile, 'logout'
AttributeError: 'NoneType' object has no attribute 'mobile'
